name: Burman
favicon: null
layout_spectrum: 0.3354096473194659
typography_spectrum: 0.030603384133428335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13534636772237718
  lightness: 0.1761023320723325
  saturation: 0.9438293722923845
  rhythmicContrast: 0.41967230825684965
purpose: []
